# -*- coding: utf-8 -*-
"""EngAtributos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-7AXtqvHUPbp8r6dF95l47Fv3chnknAr
"""

import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler

dataset = pd.read_csv('credit_simple.csv', sep=';')
dataset.shape

y = dataset['CLASSE']
x = dataset.iloc[:,:-1]
x.isnull().sum()

mediana = x['SALDO_ATUAL'].median()
mediana

x['SALDO_ATUAL'].fillna(mediana, inplace=True)
x.isnull().sum()

agrupado = x.groupby(['ESTADOCIVIL']).size()
agrupado

x['ESTADOCIVIL'].fillna('masculino solteiro', inplace=True)
x.isnull().sum()

desv = x['SALDO_ATUAL'].std()
x.loc[x['SALDO_ATUAL']>= 2 * desv, 'SALDO_ATUAL']

mediana = x['SALDO_ATUAL'].median()
x.loc[x['SALDO_ATUAL']>= 2 * desv, 'SALDO_ATUAL'] = mediana
x.loc[x['SALDO_ATUAL']>= 2 * desv]

agrupado = x.groupby(['PROPOSITO']).size()
agrupado

x.loc[x['PROPOSITO']=='Eletrodomésticos','PROPOSITO']= 'outros'
x.loc[x['PROPOSITO']=='qualificação','PROPOSITO']= 'outros'
agrupado = x.groupby(['PROPOSITO']).size()
agrupado

x['DATA']

x['DATA'] = pd.to_datetime(x['DATA'], format='%d/%m/%Y')
  x['DATA']

x['ANO'] = x['DATA'].dt.year
x['MES'] = x['DATA'].dt.month
x['DIASEMANA'] = x['DATA'].dt.day_name()
x['DIASEMANA']

x['ESTADOCIVIL'].unique()

x['PROPOSITO'].unique()

x['DIASEMANA'].unique()

labelencoder1 = LabelEncoder()
x['ESTADOCIVIL'] = labelencoder1.fit_transform(x['ESTADOCIVIL'])

x['PROPOSITO'] = labelencoder1.fit_transform(x['PROPOSITO'])

x['DIASEMANA'] = labelencoder1.fit_transform(x['DIASEMANA'])
x.head()

z= pd.get_dummies(x['OUTROSPLANOSPGTO'],prefix='OUTROS')

sc = StandardScaler()
m = sc.fit_transform(x.iloc[:,0:3])
m
x = pd.concat([x,z,pd.DataFrame(m,columns=['SALDO_ATUAL_N','RESIDENCIADESDE_N','IDADE_N'])],axis=1)
x.head()





x.drop(columns=['SALDO_ATUAL','RESIDENCIADESDE', 'IDADE', 'OUTROSPLANOSPGTO', 'DATA', 'OUTROS_banco'], inplace=True)
x.head()